[versions]

gradle-shadow = "8.3.6"

paperweight-userdev = "2.0.0-beta.18"
pluginyml-bukkit = "0.6.0"
fabric-loom = "1.14-SNAPSHOT"

adventure-api = "4.20.0"

slf4j = "2.0.17"
jspecify = "1.0.0"
checkerframework = "3.49.2"

configurate = "4.1.2"
fastutil = "8.5.15"
brigadier = "1.0.18"

google-guava = "33.4.8-jre"
google-gson = "2.13.0"

paper-api = "1.21.5-R0.1-SNAPSHOT"
bstats = "3.1.0"

run-paper = "2.3.1"
netty = "4.1.121.Final"

# generic fabric
fabric-loader = "0.18.4"

# fabric 1.21.4
minecraft-v1214 = "1.21.4"
fabricapi-v1214 = "0.119.3+1.21.4"
parchment-v1214 = "2025.03.23"
fabric-permissions-v1214 = "0.3.3"
adventure-platform-fabric-v1214 = "6.3.0"

# fabric 1.21.5
minecraft-v1215 = "1.21.5"
fabricapi-v1215 = "0.128.1+1.21.5"
parchment-v1215 = "2025.06.01"
adventure-platform-fabric-v1215 = "6.4.0"

# fabric 1.21.6/1.21.7
fabricapi-v1216 = "0.128.2+1.21.6"
minecraft-v1217 = "1.21.7"
fabricapi-v1217 = "0.129.0+1.21.7"
parchment-v1217 = "2025.06.29"
fabric-permissions-v1217 = "0.4.1"
adventure-platform-fabric-v1217 = "6.6.0"

# fabric 1.21.9
minecraft-v1219 = "1.21.9"
fabricapi-v1219 = "0.134.1+1.21.9"
parchment-v1219 = "2025.10.05"
fabric-permissions-v1219 = "0.5.0"
adventure-platform-fabric-v1219 = "6.7.0"

[plugins]
gradle-shadow = { id = "com.gradleup.shadow", version.ref = "gradle-shadow" }

paperweight-userdev = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight-userdev" }
pluginyml-bukkit = { id = "net.minecrell.plugin-yml.bukkit", version.ref = "pluginyml-bukkit" }
fabric-loom = { id = "net.fabricmc.fabric-loom-remap", version.ref = "fabric-loom" }

runtask-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }

[libraries]
adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure-api" }

slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
checkerframework = { module = "org.checkerframework:checker-qual", version.ref = "checkerframework" }

configurate-core = { module = "org.spongepowered:configurate-core", version.ref = "configurate" }
configurate-yaml = { module = "org.spongepowered:configurate-yaml", version.ref = "configurate" }

fastutil = { module = "it.unimi.dsi:fastutil", version.ref = "fastutil" }
brigadier = { module = "com.mojang:brigadier", version.ref = "brigadier" }

google-guava = { module = "com.google.guava:guava", version.ref = "google-guava" }
google-gson = { module = "com.google.code.gson:gson", version.ref = "google-gson" }

paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }
bstats = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }
netty-all = { module = "io.netty:netty-all", version.ref = "netty" }

fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }

minecraft-v1214 = { module = "com.mojang:minecraft", version.ref = "minecraft-v1214" }
fabricapi-v1214 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabricapi-v1214" }
parchment-v1214 = { module = "org.parchmentmc.data:parchment-1.21.4", version.ref = "parchment-v1214" }
fabric-permissions-v1214 = { module = "me.lucko:fabric-permissions-api", version.ref = "fabric-permissions-v1214" }
adventure-platform-fabric-v1214 = { module = "net.kyori:adventure-platform-fabric", version.ref = "adventure-platform-fabric-v1214" }

minecraft-v1215 = { module = "com.mojang:minecraft", version.ref = "minecraft-v1215" }
fabricapi-v1215 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabricapi-v1215" }
parchment-v1215 = { module = "org.parchmentmc.data:parchment-1.21.5", version.ref = "parchment-v1215" }
adventure-platform-fabric-v1215 = { module = "net.kyori:adventure-platform-fabric", version.ref = "adventure-platform-fabric-v1215" }

fabricapi-v1216 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabricapi-v1216" }
minecraft-v1217 = { module = "com.mojang:minecraft", version.ref = "minecraft-v1217" }
fabricapi-v1217 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabricapi-v1217" }
parchment-v1217 = { module = "org.parchmentmc.data:parchment-1.21.6", version.ref = "parchment-v1217" }
fabric-permissions-v1217 = { module = "me.lucko:fabric-permissions-api", version.ref = "fabric-permissions-v1217" }
adventure-platform-fabric-v1217 = { module = "net.kyori:adventure-platform-fabric", version.ref = "adventure-platform-fabric-v1217" }

minecraft-v1219 = { module = "com.mojang:minecraft", version.ref = "minecraft-v1219" }
fabricapi-v1219 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabricapi-v1219" }
parchment-v1219 = { module = "org.parchmentmc.data:parchment-1.21.9", version.ref = "parchment-v1219" }
fabric-permissions-v1219 = { module = "me.lucko:fabric-permissions-api", version.ref = "fabric-permissions-v1219" }
adventure-platform-fabric-v1219 = { module = "net.kyori:adventure-platform-fabric", version.ref = "adventure-platform-fabric-v1219" }
